#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
'''
    Title: pDNA insert seq extraction
    Date last modified: 2020/10/26
    Python Version: 3.6.2
'''
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##

# Rules -----------------------------------------------------------------------

rule all:
    input:
        'data/pDNA_insert_seq/processed/6185_1_pMT06_inserts.tsv',
        'data/pDNA_insert_seq/processed/6185_1_pMT06_insert_counts.tsv',
        'pDNA_insert_seq/analysis/docs/6185_1_pMT06_CCGCGGTT-AGCGCTAG_S1_R1_001_fastqc.html'


# Extract inserts from fastq file
rule extract_inserts_from_fq:
    input:
        fq = 'data/pDNA_insert_seq/fastq_files/6185_1_pMT06_CCGCGGTT-AGCGCTAG_S1_R1_001.fastq.gz'
    output:
        tsv = 'data/pDNA_insert_seq/processed/6185_1_pMT06_inserts.tsv'
    log:
        'pDNA_insert_seq/analysis/log/extract_inserts_from_fq.log'
    conda:
        'pDNA_insert_seq/analysis/environment.yaml'
    script:
        'mt20201026_insert-counts.py'

# Cluster inserts with Starcode
rule cluster_inserts:
    input:
        starcode_in = 'data/pDNA_insert_seq/processed/6185_1_pMT06_inserts.tsv'
    output:
        ofn = 'data/pDNA_insert_seq/processed/6185_1_pMT06_insert_counts.tsv',
    log:
        'pDNA_insert_seq/analysis/log/cluster_ecn_inserts.log'
    conda:
        'pDNA_insert_seq/analysis/environment.yaml'
    threads: 12
    shell:
        'starcode --threads {threads} --print-clusters -i {input.starcode_in} --dist 3 | \
        sort -k1,1 > {output.ofn}'


# General FastQC rule
rule fastqc:
    input:
        r1 = 'data/pDNA_insert_seq/fastq_files/6185_1_pMT06_CCGCGGTT-AGCGCTAG_S1_R1_001.fastq.gz'
    output:
        'pDNA_insert_seq/analysis/docs/6185_1_pMT06_CCGCGGTT-AGCGCTAG_S1_R1_001_fastqc.html'
    params:
        out_dir='pDNA_insert_seq/analysis/docs/'
    log:
        'pDNA_insert_seq/analysis/log/6185_1_pMT06.log'
    conda:
        'pDNA_insert_seq/analysis/environment.yaml'
    threads: 8
    shell:
        """
        mkdir -p {params.out_dir}
        fastqc --outdir {params.out_dir} --threads {threads} -f fastq {input.r1}
        """
