#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
'''
    Title: BC extraction
    Date last modified: 2020/09/16
    Python Version: 3.6.2
'''
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##

include:
    '/DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/raw_data_analysis/gcf6502/config.py'

# Rules -----------------------------------------------------------------------

rule all:
    input:
        expand('/DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/data/gcf6502/results_b12_d1/{ecn}_barcode_counts.tsv', ecn = ECN)


# Extract barcodes from cDNA/pDNA SE fastq files
rule extract_barcodes_from_fq:
    input:
        fq = ECN_DIR + S1
    output:
        tsv = '/DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/data/gcf6502/results_b12_d1/{ecn}_barcodes.tsv'
    log:
        '/DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/data/gcf6502/logs_b12_d1/{ecn}_extract_barcodes_from_fq.log'
    conda:
        '/DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/raw_data_analysis/gcf6502/environment.yaml'
    script:
        '/DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/raw_data_analysis/gcf6502/mt20201117_bc-counts.py'

# Cluster cDNA/pDNA barcodes with Starcode

rule cluster_ecn_barcodes:
    input:
        starcode_in = '/DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/data/gcf6502/results_b12_d1/{ecn}_barcodes.tsv'
    output:
        ofn = '/DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/data/gcf6502/results_b12_d1/{ecn}_barcode_counts.tsv',
    log:
        '/DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/data/gcf6502/logs_b12_d1/{ecn}_cluster_ecn_barcodes.log'
    conda:
        '/DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/raw_data_analysis/gcf6502/environment.yaml'
    threads: 12
    shell:
        'starcode --threads {threads} --print-clusters -i {input.starcode_in} --dist 1 | \
        sort -k1,1 > {output.ofn}'
